---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue95
description: A desktop for your childhood home's computer room

base-image: ghcr.io/winblues/vauxite
image-version: 42

modules:

  - type: bling
    install:
      - 1password

  - type: dnf
    install:
      packages:
      - audacious
      - btop
      - catfish
      - edk2-ovmf
      - libvirt
      - libvirt-nss
      - libcanberra-gtk3
      - lightdm-gtk-greeter-settings
      - mate-disk-usage-analyzer
      - mate-system-monitor
      - menulibre
      - neovim
      - orage
      - patch
      - podman-compose
      - podman-machine
      - python3-cairosvg
      - plymouth-plugin-script
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - qemu
      - qt5ct
      - qt5-qtstyleplugins
      - sox
      - strace
      - virt-manager
      - vorbis-tools
      - wine-ms-sans-serif-fonts
      - wine-tahoma-fonts
      - xorg-x11-server-Xephyr # to test lightdm
      - xscreensaver-extras
      - xscreensaver-extras-gss
      # Chicago95 Plus!
      - inkscape
      - xcursorgen
      - python3-svgwrite
      - python3-fonttools
      - python3-numpy
      # Installer packages
      - python3-pillow
      - python3-gobject
      - gtk3
      - kmines
      # Fix taskbar icons for Xfce 4.20
      - gdk-pixbuf2-modules-extra
      # TODO: this is for Paint and we should package it properly and not
      # install its deps directly on the image here
      - webkit2gtk3
      # Raw RPMs
      - https://github.com/felixrieseberg/clippy/releases/download/v0.4.0/Clippy-0.4.0-1.x86_64.rpm

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - 'cd $CONFIG_DIRECTORY/scripts && for script in *.sh; do [ -f "$script" ] && bash "$script" || exit 1; done'

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished
    user: {} # Just add Flathub
    system:
      # Flathub will be used by default
      install:
        - com.github.k4zmu2a.spacecadetpinball
        - org.gtk.Gtk3theme.Chicago95
        - com.tomjwatson.Emote
        - org.geany.Geany
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox

  # Regenerate initramfs because of plymouth
  - type: initramfs

  - type: signing

