name: generate-iso
on:
  push:
    branches:
      - livecd-iso
  schedule:
    - cron:
        "00 10 * * 1" # build at 10:00 UTC every Monday
  workflow_dispatch:

jobs:
  iso:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

      - name: Checkout Titanoboa
        uses: actions/checkout@v4
        with:
          repository: "ledif/titanoboa"
          path: "titanoboa"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y just podman

      - name: Build ISO
        run: |
          cd titanoboa
          cat Justfile
          id -a
          just build ghcr.io/winblues/blue95:latest 1

      - name: Upload ISOs and Checksum to R2
        #        if: github.ref_name == 'main'
        shell: bash
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_REGION: auto
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
          rclone copyto titanoboa/output.iso R2:ublue-ledif/blue95-live.iso
